// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyv7FimoMpT9UYKCVqK5jMEZe50hyCzEo',
    appId: '1:506222579778:web:e214a4de09eee3ee529ddb',
    messagingSenderId: '506222579778',
    projectId: 'chatapp-14a26',
    authDomain: 'chatapp-14a26.firebaseapp.com',
    storageBucket: 'chatapp-14a26.firebasestorage.app',
    measurementId: 'G-PKTKLNNHJ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeTkYKS4iRYrPo-0Eu7RMpQBj1KJg5Buc',
    appId: '1:506222579778:android:ad145322309f5731529ddb',
    messagingSenderId: '506222579778',
    projectId: 'chatapp-14a26',
    storageBucket: 'chatapp-14a26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAodQNmeVFyDeu80OjsPddB38SsPoFkjW0',
    appId: '1:506222579778:ios:b28ae731447b644b529ddb',
    messagingSenderId: '506222579778',
    projectId: 'chatapp-14a26',
    storageBucket: 'chatapp-14a26.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAodQNmeVFyDeu80OjsPddB38SsPoFkjW0',
    appId: '1:506222579778:ios:b28ae731447b644b529ddb',
    messagingSenderId: '506222579778',
    projectId: 'chatapp-14a26',
    storageBucket: 'chatapp-14a26.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyv7FimoMpT9UYKCVqK5jMEZe50hyCzEo',
    appId: '1:506222579778:web:c8be865c9d56d83a529ddb',
    messagingSenderId: '506222579778',
    projectId: 'chatapp-14a26',
    authDomain: 'chatapp-14a26.firebaseapp.com',
    storageBucket: 'chatapp-14a26.firebasestorage.app',
    measurementId: 'G-W0BVXCEZ1E',
  );
}
